## Import Libraries and all data set 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:\\dialect_all.csv',encoding="UTF-8")

In [3]:
df

id dialect  \
0       1175358310087892992      IQ   
1       1175416117793349632      IQ   
2       1175450108898565888      IQ   
3       1175471073770573824      IQ   
4       1175496913145217024      IQ   
...                     ...     ...   
458192  1019484980282580992      BH   
458193  1021083283709407232      BH   
458194  1017477537889431552      BH   
458195  1022430374696239232      BH   
458196  1022409931029458944      BH   

                                                 response  
0        @Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .  
1       @7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...  
2                         @KanaanRema مبين من كلامه خليجي  
3              @HAIDER76128900 يسلملي مرورك وروحك الحلوه💐  
4                      @hmo2406 وين هل الغيبه  اخ محمد 🌸🌺  
...                                                   ...  
458192              @Al_mhbaa_7 مبسوطين منك اللي باسطانا😅  
458193       @Zzainabali @P_ameerah والله ماينده ابش يختي  
458194  @Al_mhbaa_7 شو عملنا لك حنا تهربي مننا احنا مس...  
458195        @haneenalmwla الله يبارك فيها وبالعافيه 😋😋😋  
458196          @jolnar121 السحله ضيفي ي بتطلع لك سحليه😅😅  

[458197 rows x 3 columns]

In [4]:
df = df.drop('id', 1) # drop first(id) column


In [5]:
df

dialect                                           response
0           IQ   @Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .
1           IQ  @7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...
2           IQ                    @KanaanRema مبين من كلامه خليجي
3           IQ         @HAIDER76128900 يسلملي مرورك وروحك الحلوه💐
4           IQ                 @hmo2406 وين هل الغيبه  اخ محمد 🌸🌺
...        ...                                                ...
458192      BH              @Al_mhbaa_7 مبسوطين منك اللي باسطانا😅
458193      BH       @Zzainabali @P_ameerah والله ماينده ابش يختي
458194      BH  @Al_mhbaa_7 شو عملنا لك حنا تهربي مننا احنا مس...
458195      BH        @haneenalmwla الله يبارك فيها وبالعافيه 😋😋😋
458196      BH          @jolnar121 السحله ضيفي ي بتطلع لك سحليه😅😅

[458197 rows x 2 columns]

In [6]:
columns_titles = ["response","dialect"]
df=df.reindex(columns=columns_titles)  #swap el columns

In [7]:
df

response dialect
0        @Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .      IQ
1       @7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...      IQ
2                         @KanaanRema مبين من كلامه خليجي      IQ
3              @HAIDER76128900 يسلملي مرورك وروحك الحلوه💐      IQ
4                      @hmo2406 وين هل الغيبه  اخ محمد 🌸🌺      IQ
...                                                   ...     ...
458192              @Al_mhbaa_7 مبسوطين منك اللي باسطانا😅      BH
458193       @Zzainabali @P_ameerah والله ماينده ابش يختي      BH
458194  @Al_mhbaa_7 شو عملنا لك حنا تهربي مننا احنا مس...      BH
458195        @haneenalmwla الله يبارك فيها وبالعافيه 😋😋😋      BH
458196          @jolnar121 السحله ضيفي ي بتطلع لك سحليه😅😅      BH

[458197 rows x 2 columns]

In [8]:
#df2 = df.iloc[:100000,:] #use first 100000 row

In [9]:
df2 = df

In [10]:
i = 0
while i < len(df2):
    for row in df2['response']:
        y = row.replace('؟', '') 
        df2.at[i,'response'] = y
        i =i+1


In [11]:
def remove_english_string(string):
    return " ".join(re.findall('[\u0600-\u06ff]+', string))
  



In [12]:
x = 'x'
i = 0

In [13]:
import re

In [14]:
#remove Emojes
while i < len(df2):
    for row in df2['response']:
        y = remove_english_string(row)
        df2.at[i,'response'] = y          
        i=i+1
    else:
            break;
    
    

In [15]:
df2

response dialect
0                                 لكن بالنهاية ينتفض يغير      IQ
1       يعني هذا محسوب على البشر حيونه ووحشيه وتطلبون ...      IQ
2                                     مبين من كلامه خليجي      IQ
3                               يسلملي مرورك وروحك الحلوه      IQ
4                                   وين هل الغيبه اخ محمد      IQ
...                                                   ...     ...
458192                           مبسوطين منك اللي باسطانا      BH
458193                              والله ماينده ابش يختي      BH
458194  شو عملنا لك حنا تهربي مننا احنا مساكين ليش بتع...      BH
458195                          الله يبارك فيها وبالعافيه      BH
458196                       السحله ضيفي ي بتطلع لك سحليه      BH

[458197 rows x 2 columns]

In [16]:
df3 = pd.get_dummies(df2, columns=['dialect']) # for dummy colums

In [17]:
df3

response  dialect_AE  \
0                                 لكن بالنهاية ينتفض يغير           0   
1       يعني هذا محسوب على البشر حيونه ووحشيه وتطلبون ...           0   
2                                     مبين من كلامه خليجي           0   
3                               يسلملي مرورك وروحك الحلوه           0   
4                                   وين هل الغيبه اخ محمد           0   
...                                                   ...         ...   
458192                           مبسوطين منك اللي باسطانا           0   
458193                              والله ماينده ابش يختي           0   
458194  شو عملنا لك حنا تهربي مننا احنا مساكين ليش بتع...           0   
458195                          الله يبارك فيها وبالعافيه           0   
458196                       السحله ضيفي ي بتطلع لك سحليه           0   

        dialect_BH  dialect_DZ  dialect_EG  dialect_IQ  dialect_JO  \
0                0           0           0           1           0   
1                0           0           0           1           0   
2                0           0           0           1           0   
3                0           0           0           1           0   
4                0           0           0           1           0   
...            ...         ...         ...         ...         ...   
458192           1           0           0           0           0   
458193           1           0           0           0           0   
458194           1           0           0           0           0   
458195           1           0           0           0           0   
458196           1           0           0           0           0   

        dialect_KW  dialect_LB  dialect_LY  dialect_MA  dialect_OM  \
0                0           0           0           0           0   
1                0           0           0           0           0   
2                0           0           0           0           0   
3                0           0           0           0           0   
4                0           0           0           0           0   
...            ...         ...         ...         ...         ...   
458192           0           0           0           0           0   
458193           0           0           0           0           0   
458194           0           0           0           0           0   
458195           0           0           0           0           0   
458196           0           0           0           0           0   

        dialect_PL  dialect_QA  dialect_SA  dialect_SD  dialect_SY  \
0                0           0           0           0           0   
1                0           0           0           0           0   
2                0           0           0           0           0   
3                0           0           0           0           0   
4                0           0           0           0           0   
...            ...         ...         ...         ...         ...   
458192           0           0           0           0           0   
458193           0           0           0           0           0   
458194           0           0           0           0           0   
458195           0           0           0           0           0   
458196           0           0           0           0           0   

        dialect_TN  dialect_YE  
0                0           0  
1                0           0  
2                0           0  
3                0           0  
4                0           0  
...            ...         ...  
458192           0           0  
458193           0           0  
458194           0           0  
458195           0           0  
458196           0           0  

[458197 rows x 19 columns]

In [18]:
X_final = df3['response']

In [19]:
X_final

0                                   لكن بالنهاية ينتفض يغير
1         يعني هذا محسوب على البشر حيونه ووحشيه وتطلبون ...
2                                       مبين من كلامه خليجي
3                                 يسلملي مرورك وروحك الحلوه
4                                     وين هل الغيبه اخ محمد
                                ...                        
458192                             مبسوطين منك اللي باسطانا
458193                                والله ماينده ابش يختي
458194    شو عملنا لك حنا تهربي مننا احنا مساكين ليش بتع...
458195                            الله يبارك فيها وبالعافيه
458196                         السحله ضيفي ي بتطلع لك سحليه
Name: response, Length: 458197, dtype: object

In [20]:
y_final = df3.drop(['response'], axis = 1)

In [21]:
y_final

dialect_AE  dialect_BH  dialect_DZ  dialect_EG  dialect_IQ  \
0                0           0           0           0           1   
1                0           0           0           0           1   
2                0           0           0           0           1   
3                0           0           0           0           1   
4                0           0           0           0           1   
...            ...         ...         ...         ...         ...   
458192           0           1           0           0           0   
458193           0           1           0           0           0   
458194           0           1           0           0           0   
458195           0           1           0           0           0   
458196           0           1           0           0           0   

        dialect_JO  dialect_KW  dialect_LB  dialect_LY  dialect_MA  \
0                0           0           0           0           0   
1                0           0           0           0           0   
2                0           0           0           0           0   
3                0           0           0           0           0   
4                0           0           0           0           0   
...            ...         ...         ...         ...         ...   
458192           0           0           0           0           0   
458193           0           0           0           0           0   
458194           0           0           0           0           0   
458195           0           0           0           0           0   
458196           0           0           0           0           0   

        dialect_OM  dialect_PL  dialect_QA  dialect_SA  dialect_SD  \
0                0           0           0           0           0   
1                0           0           0           0           0   
2                0           0           0           0           0   
3                0           0           0           0           0   
4                0           0           0           0           0   
...            ...         ...         ...         ...         ...   
458192           0           0           0           0           0   
458193           0           0           0           0           0   
458194           0           0           0           0           0   
458195           0           0           0           0           0   
458196           0           0           0           0           0   

        dialect_SY  dialect_TN  dialect_YE  
0                0           0           0  
1                0           0           0  
2                0           0           0  
3                0           0           0  
4                0           0           0  
...            ...         ...         ...  
458192           0           0           0  
458193           0           0           0  
458194           0           0           0  
458195           0           0           0  
458196           0           0           0  

[458197 rows x 18 columns]

In [22]:
X_final

0                                   لكن بالنهاية ينتفض يغير
1         يعني هذا محسوب على البشر حيونه ووحشيه وتطلبون ...
2                                       مبين من كلامه خليجي
3                                 يسلملي مرورك وروحك الحلوه
4                                     وين هل الغيبه اخ محمد
                                ...                        
458192                             مبسوطين منك اللي باسطانا
458193                                والله ماينده ابش يختي
458194    شو عملنا لك حنا تهربي مننا احنا مساكين ليش بتع...
458195                            الله يبارك فيها وبالعافيه
458196                         السحله ضيفي ي بتطلع لك سحليه
Name: response, Length: 458197, dtype: object

In [23]:
from sklearn.model_selection import train_test_split #
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.3, random_state=42,stratify=y_final)

In [24]:
y_train

dialect_AE  dialect_BH  dialect_DZ  dialect_EG  dialect_IQ  \
239341           0           0           1           0           0   
340328           0           0           0           0           0   
413933           1           0           0           0           0   
229567           0           0           1           0           0   
271795           0           0           0           1           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           1           0   
304293           0           0           0           0           0   
214293           0           0           0           0           0   
34959            0           0           0           0           0   
315079           0           0           0           0           0   

        dialect_JO  dialect_KW  dialect_LB  dialect_LY  dialect_MA  \
239341           0           0           0           0           0   
340328           0           1           0           0           0   
413933           0           0           0           0           0   
229567           0           0           0           0           0   
271795           0           0           0           0           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           0           0   
304293           0           0           1           0           0   
214293           0           0           0           0           0   
34959            0           0           0           1           0   
315079           0           0           1           0           0   

        dialect_OM  dialect_PL  dialect_QA  dialect_SA  dialect_SD  \
239341           0           0           0           0           0   
340328           0           0           0           0           0   
413933           0           0           0           0           0   
229567           0           0           0           0           0   
271795           0           0           0           0           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           0           0   
304293           0           0           0           0           0   
214293           0           0           0           1           0   
34959            0           0           0           0           0   
315079           0           0           0           0           0   

        dialect_SY  dialect_TN  dialect_YE  
239341           0           0           0  
340328           0           0           0  
413933           0           0           0  
229567           0           0           0  
271795           0           0           0  
...            ...         ...         ...  
300281           0           0           0  
304293           0           0           0  
214293           0           0           0  
34959            0           0           0  
315079           0           0           0  

[320737 rows x 18 columns]

In [25]:
from collections import Counter


In [26]:


def counter_word(text):
    count = Counter()
    for i in text.values:
        for word in i.split():
            count[word] +=1
    return count            

In [27]:
text = X_train
counter = counter_word(text)

In [28]:
len(counter)

423865

In [29]:
counter

Counter({'الناس': 9264,
         'واش': 676,
         'تفكر': 211,
         'يستغلو': 5,
         'صلاة': 210,
         'في': 50442,
         'مسجد': 91,
         'باش': 1272,
         'يرشحوهم': 1,
         'الله': 34623,
         'يزيدنا': 4,
         'عقل': 301,
         'شى': 74,
         'خيااااااال': 3,
         '،': 15158,
         'اتمنى': 582,
         'أني': 282,
         'اشوف': 1251,
         'هالأشياء': 18,
         'بديرته': 15,
         'اللي': 41717,
         'ما': 51950,
         'ينقصها': 12,
         'شي': 13790,
         'الصفقه': 19,
         'الي': 8495,
         'نباها': 5,
         'جدامها': 3,
         '٢١': 26,
         'يوم': 6961,
         'ممكن': 4662,
         'تسجلها': 1,
         'يعني': 9278,
         'ثقلان': 1,
         'مو': 8391,
         'ثقل': 33,
         'واحد': 8469,
         'يا': 30663,
         'الهوا': 228,
         'تريند': 20,
         'ظابط': 42,
         'امن': 177,
         'الدوله': 339,
         'بتاعك': 64,
         'ده': 7434,
    

In [30]:
num_word = len(counter)

max_length = 20

# Tokinez the data set 

In [31]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=num_word)
tokenizer.fit_on_texts(X_train)

Using TensorFlow backend.


In [32]:
word_index = tokenizer.word_index

In [33]:
word_index

{'من': 1,
 'ما': 2,
 'في': 3,
 'و': 4,
 'اللي': 5,
 'الله': 6,
 'بس': 7,
 'على': 8,
 'يا': 9,
 'مش': 10,
 'كل': 11,
 'انا': 12,
 'ولا': 13,
 'لا': 14,
 'والله': 15,
 '،': 16,
 'لو': 17,
 'شي': 18,
 'مع': 19,
 'انت': 20,
 'ان': 21,
 'عن': 22,
 'كان': 23,
 'ع': 24,
 'هذا': 25,
 'هو': 26,
 'عشان': 27,
 'فيه': 28,
 'يعني': 29,
 'الناس': 30,
 'بعد': 31,
 'الي': 32,
 'واحد': 33,
 'مو': 34,
 'علي': 35,
 'اذا': 36,
 'او': 37,
 'غير': 38,
 'لما': 39,
 'ده': 40,
 'حتى': 41,
 'يوم': 42,
 'اي': 43,
 'فيها': 44,
 'شو': 45,
 'انه': 46,
 'ف': 47,
 'ليش': 48,
 'لكن': 49,
 'وين': 50,
 'لي': 51,
 'عليه': 52,
 'الا': 53,
 'لازم': 54,
 'راح': 55,
 'احنا': 56,
 'حد': 57,
 'قبل': 58,
 'دي': 59,
 'ناس': 60,
 'عليك': 61,
 'لك': 62,
 'ايه': 63,
 'اليوم': 64,
 'ممكن': 65,
 'كيف': 66,
 'له': 67,
 'كنت': 68,
 'يارب': 69,
 'هي': 70,
 'ربي': 71,
 'أنا': 72,
 'عم': 73,
 'شاء': 74,
 'وانا': 75,
 'زي': 76,
 'صار': 77,
 'فى': 78,
 'يكون': 79,
 'مين': 80,
 'مثل': 81,
 'خير': 82,
 'صح': 83,
 'عندي': 84,
 'هذي': 85,
 'مصر

In [34]:
num_words = len(word_index)

In [35]:
num_words

423865

In [36]:
train_sequences = tokenizer.texts_to_sequences(X_train)

In [37]:
train_sequences[0]

[30, 623, 2209, 60644, 2217, 3, 5163, 301, 166973, 6, 70810, 1505]

## Train Model

In [38]:
from keras.preprocessing.sequence import pad_sequences


In [39]:
max_length = 20

In [40]:
train_padded = pad_sequences(train_sequences, maxlen=max_length,padding='post',truncating='post')

In [41]:
train_padded[0]

array([    30,    623,   2209,  60644,   2217,      3,   5163,    301,
       166973,      6,  70810,   1505,      0,      0,      0,      0,
            0,      0,      0,      0])

In [42]:
test_sequences = tokenizer.texts_to_sequences(X_test)
test_padded = pad_sequences(test_sequences, maxlen=max_length,padding='post',truncating='post')

In [43]:
test_padded

array([[    12,     77,     51, ...,      0,      0,      0],
       [132864,    128,      3, ...,      0,      0,      0],
       [   782,    380,   7158, ...,    117,     57,      7],
       ...,
       [     1, 116054,   3030, ...,      0,      0,      0],
       [     7,    606,     11, ...,      0,      0,      0],
       [  2887,  16019,   6868, ...,      0,      0,      0]])

In [44]:
print(X_train[0])

لكن بالنهاية ينتفض يغير


In [45]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.initializers import Constant
from tensorflow.keras.optimizers import Adam


In [46]:


model = Sequential()

model.add(Embedding(num_words,32,input_length=max_length))
model.add(LSTM(64,dropout=0.1))
model.add(Dense(18,activation='sigmoid'))

optimizer = Adam(learning_rate=3e-4)


model.compile(loss='binary_crossentropy',optimizer=optimizer, metrics=['accuracy'])

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 32)            13563680  
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                24832     
_________________________________________________________________
dense_1 (Dense)              (None, 18)                1170      
Total params: 13,589,682
Trainable params: 13,589,682
Non-trainable params: 0
_________________________________________________________________


In [48]:
y_train

dialect_AE  dialect_BH  dialect_DZ  dialect_EG  dialect_IQ  \
239341           0           0           1           0           0   
340328           0           0           0           0           0   
413933           1           0           0           0           0   
229567           0           0           1           0           0   
271795           0           0           0           1           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           1           0   
304293           0           0           0           0           0   
214293           0           0           0           0           0   
34959            0           0           0           0           0   
315079           0           0           0           0           0   

        dialect_JO  dialect_KW  dialect_LB  dialect_LY  dialect_MA  \
239341           0           0           0           0           0   
340328           0           1           0           0           0   
413933           0           0           0           0           0   
229567           0           0           0           0           0   
271795           0           0           0           0           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           0           0   
304293           0           0           1           0           0   
214293           0           0           0           0           0   
34959            0           0           0           1           0   
315079           0           0           1           0           0   

        dialect_OM  dialect_PL  dialect_QA  dialect_SA  dialect_SD  \
239341           0           0           0           0           0   
340328           0           0           0           0           0   
413933           0           0           0           0           0   
229567           0           0           0           0           0   
271795           0           0           0           0           0   
...            ...         ...         ...         ...         ...   
300281           0           0           0           0           0   
304293           0           0           0           0           0   
214293           0           0           0           1           0   
34959            0           0           0           0           0   
315079           0           0           0           0           0   

        dialect_SY  dialect_TN  dialect_YE  
239341           0           0           0  
340328           0           0           0  
413933           0           0           0  
229567           0           0           0  
271795           0           0           0  
...            ...         ...         ...  
300281           0           0           0  
304293           0           0           0  
214293           0           0           0  
34959            0           0           0  
315079           0           0           0  

[320737 rows x 18 columns]

In [49]:
y_test = y_test.to_numpy()

In [50]:
y_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [51]:
test_padded

array([[    12,     77,     51, ...,      0,      0,      0],
       [132864,    128,      3, ...,      0,      0,      0],
       [   782,    380,   7158, ...,    117,     57,      7],
       ...,
       [     1, 116054,   3030, ...,      0,      0,      0],
       [     7,    606,     11, ...,      0,      0,      0],
       [  2887,  16019,   6868, ...,      0,      0,      0]])

In [52]:
len(X_train)

320737

In [53]:
model.fit(train_padded,y_train,epochs=9, validation_data=(test_padded,y_test))

Train on 320737 samples, validate on 137460 samples
Epoch 1/9
320737/320737 [==============================] - 921s 3ms/step - loss: 0.1876 - accuracy: 0.9459 - val_loss: 0.1588 - val_accuracy: 0.9492
Epoch 2/9
320737/320737 [==============================] - 913s 3ms/step - loss: 0.1420 - accuracy: 0.9530 - val_loss: 0.1445 - val_accuracy: 0.9535
Epoch 3/9
320737/320737 [==============================] - 971s 3ms/step - loss: 0.1171 - accuracy: 0.9604 - val_loss: 0.1404 - val_accuracy: 0.9551
Epoch 4/9
320737/320737 [==============================] - 976s 3ms/step - loss: 0.0966 - accuracy: 0.9675 - val_loss: 0.1437 - val_accuracy: 0.9543
Epoch 5/9
320737/320737 [==============================] - 978s 3ms/step - loss: 0.0801 - accuracy: 0.9735 - val_loss: 0.1502 - val_accuracy: 0.9531
Epoch 6/9
320737/320737 [==============================] - 974s 3ms/step - loss: 0.0669 - accuracy: 0.9782 - val_loss: 0.1544 - val_accuracy: 0.9528
Epoch 7/9
320737/320737 [=============================

In [54]:
ynew = model.predict_classes(test_padded) #pedicted labels

In [55]:
ynew

array([ 6,  0,  7, ..., 10, 11,  8], dtype=int64)

In [56]:
y_test     # True labels in One Hot encoding form

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [57]:
y_test_number = np.argmax(y_test, axis = 1) # Convert one_hot vector to decimal number 

In [58]:
print('Length of True Labels = ',len(y_test_number))
print('Length of Predicated Labels = ',len(ynew))

Length of True Labels =  137460
Length of Predicated Labels =  137460


In [59]:
# Precision 
from sklearn.metrics import precision_score
precision = precision_score(y_test_number, ynew, average='micro')
print('Precision: %.3f' % precision)

Precision: 0.468


In [60]:
# Recall
from sklearn.metrics import recall_score
recall = recall_score(y_test_number, ynew, average='micro')
print('Recall: %.3f' % recall)

Recall: 0.468


In [61]:
from sklearn.metrics import f1_score

score = f1_score(y_test_number, ynew, average='weighted')
print('F1_Score: %.3f' % score)

F1_Score: 0.466


In [62]:
#model.fit(train_padded,y_train,epochs=1, validation_data=(test_padded,y_test))